name: AIO NyanimeCoder

on:
  workflow_dispatch:
    inputs:
      AniCode:
        description: "AniCode"
        required: true
        type: choice
        options:
        - "angelNextDoor"
        - "tomoChan"
        - "kageJitsu"
        - "demonSlayerS01"
        - "demonSlayerS02"
        - "fuuKoi"
        - "isekaiHarem"
        - "summerTime"
        - "twinStar"
        - "horiMiya"
      EpCode:
        description: "EpCode, 01..13/18/20/25/26/50"
        required: true
        type: number
      SpeedProf:
        description: "SpeedProf"
        required: true
        default: "2x576"
        type: choice
        options:
        - "0x720"
        - "0x576"
        - "2x720"
        - "2x576"
        - "1x576"
      RoughQuality:
        description: "Lower Quality?"
        required: true
        type: boolean
        default: true
      QCReport:
        description: "QC Report?"
        required: true
        type: boolean
        default: false

env:
  SOURCERY: ${{ secrets.SOURCERY }}
  AniCode: ${{ github.event.inputs.AniCode }}
  EpCode: ${{ github.event.inputs.EpCode }}
  SpeedProf: ${{ github.event.inputs.SpeedProf }}
  RoughQuality: ${{ github.event.inputs.RoughQuality }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}

jobs:
  primary:
    name: Prepare Steps for R3Encod3r
    runs-on: ubuntu-22.04

    outputs:
      AniName: ${{ steps.set-params.outputs.AniName }}
      LocationOnIndex: ${{ steps.set-params.outputs.LocationOnIndex }}
      EncSpeed: ${{ steps.set-params.outputs.EncSpeed }}
      R3NC0D3R: ${{ steps.set-params.outputs.R3NC0D3R }}
      VidRes: ${{ steps.set-params.outputs.VidRes }}
      JobPostfix: ${{ steps.set-params.outputs.JobPostfix }}
      ReSplitDataFile: ${{ steps.set-params.outputs.ReSplitDataFile }}
      matrix: ${{ steps.set-params.outputs.matrix }}
      safile_json: ${{ steps.set-params.outputs.safile_json }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "rtools"
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncSCR-ec737ccf07b7
      - name: Export MultiAnime Data
        run: |
          case "${AniCode}" in
            "angelNextDoor")
              echo "AniName=The.Angel.Next.Door.Spoils.Me.Rotten" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/The.Angel.Next.Door.Spoils.Me.Rotten.WEBRipZ" >>$GITHUB_ENV
              ;;
            "tomoChan")
              echo "AniName=Tomo-chan.Is.a.Girl" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/Tomo-chan.Is.a.Girl.WEBRipZ" >>$GITHUB_ENV
              ;;
            "kageJitsu")
              echo "AniName=The.Eminence.in.Shadow" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/The.Eminence.in.Shadow.WEBRipZ" >>$GITHUB_ENV
              ;;
            "demonSlayerS01")
              echo "AniName=Demon.Slayer.S01" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/Demon.Slayer.S01.BDRipZ" >>$GITHUB_ENV
              ;;
            "demonSlayerS02")
              echo "AniName=Demon.Slayer.S02" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/Demon.Slayer.S02.BDRipZ" >>$GITHUB_ENV
              ;;
            "fuuKoi")
              echo "AniName=Fuufu.Ijou.Koibito.Miman" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/Fuufu.Ijou.Koibito.Miman.WEBRipZ" >>$GITHUB_ENV
              ;;
            "isekaiHarem")
              echo "AniName=Isekai.Meikyuu.de.Harem.wo" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/Isekai.Meikyuu.de.Harem.wo.TVRipZ" >>$GITHUB_ENV
              ;;
            "summerTime")
              echo "AniName=Summer.Time.Rendering" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/Summer.Time.Rendering.BDRipZ" >>$GITHUB_ENV
              ;;
            "twinStar")
              echo "AniName=Twin.Star.Exorcists" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/Twin.Star.Exorcists.BDReRipZ" >>$GITHUB_ENV
              ;;
            "horiMiya")
              echo "AniName=HoriMiya" >>$GITHUB_ENV
              echo "LocationOnIndex=td:/HoriMiya.BDRipZ" >>$GITHUB_ENV
              ;;
          esac
      - name: Create EncMatrix
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./41-EncSCR-398b818acdae
      - name: Export Parameters
        id: set-params
        run: |
          echo "AniName=${AniName}" >> $GITHUB_OUTPUT
          echo "LocationOnIndex=${LocationOnIndex}" >> $GITHUB_OUTPUT
          echo "EncSpeed=${EncSpeed}" >> $GITHUB_OUTPUT
          echo "R3NC0D3R=${R3NC0D3R}" >> $GITHUB_OUTPUT
          echo "VidRes=${VidRes}" >> $GITHUB_OUTPUT
          echo "JobPostfix=${JobPostfix}" >> $GITHUB_OUTPUT
          echo "ReSplitDataFile=${ReSplitDataFile}" >> $GITHUB_OUTPUT
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
          echo "safile_json=${safile_json}" >> $GITHUB_OUTPUT

  enc_nyaanime:
    name: Encode Phase
    runs-on: ubuntu-22.04
    needs: primary

    strategy:
      fail-fast: false
      max-parallel: 18
      matrix:
        ChunkNum: ${{fromJson(needs.primary.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "ftools rtools"
          safile_json: ${{ needs.primary.outputs.safile_json }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncSCR-ec737ccf07b7
      - name: ${{env.R3NC0D3R}} R3NC0D3R - Chunk_${{env.ChunkNum}} of ${{env.AniCode}} - Ep${{env.EpCode}}
        env:
          ChunkNum: ${{ matrix.ChunkNum }}
          AniName: ${{ needs.primary.outputs.AniName }}
          LocationOnIndex: ${{ needs.primary.outputs.LocationOnIndex }}
          EncSpeed: ${{ needs.primary.outputs.EncSpeed }}
          R3NC0D3R: ${{ needs.primary.outputs.R3NC0D3R }}
          VidRes: ${{ needs.primary.outputs.VidRes }}
          ReSplitDataFile: ${{ needs.primary.outputs.ReSplitDataFile }}
          JobPostfix: ${{ needs.primary.outputs.JobPostfix }}
          QCReport: ${{ github.event.inputs.QCReport }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./61-EncSCR-5326ae6ccfd1

  postEnc:
    name: Merge Episode
    runs-on: ubuntu-22.04
    needs: [primary, enc_nyaanime]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "ftools rtools"
          safile_json: ${{ needs.primary.outputs.safile_json }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncSCR-ec737ccf07b7
      - name: Merge ${{env.AniCode}} - Ep${{env.EpCode}}
        env:
          AniName: ${{ needs.primary.outputs.AniName }}
          LocationOnIndex: ${{ needs.primary.outputs.LocationOnIndex }}
          EncSpeed: ${{ needs.primary.outputs.EncSpeed }}
          R3NC0D3R: ${{ needs.primary.outputs.R3NC0D3R }}
          VidRes: ${{ needs.primary.outputs.VidRes }}
          JobPostfix: ${{ needs.primary.outputs.JobPostfix }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY && source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./91-EncSCR-9ea49f4100df
